model_name: Pendulum
data_config_path: data_collection/data_config.yaml
train_config_path: neural_network/configs/PendulumModelTrainConfig.ini
VI_loops: 1000
controller_name: "BaseMPCController"
NN_controller_name: "NNMPCController"

resume_training: false
loop_to_resume_from: 121
VI_dir: ""