# ----------------------------------------------------------------------------------------
# CARTPOLE MODEL CONFIGURATION
# ----------------------------------------------------------------------------------------
cartpole:
  mujoco:
    urdf_available: false
    model_path: "models_xml/cartpole.xml"
    sim_timestep: 0.001 # seconds
    sim_duration: 5 # seconds
    sim_framerate: 30  # Hz
    render: true # Render simulation
    verbose: false # Print debug information
    resolution: [480, 640]

  model:
    name: "cartpole"
    mass:
      cart: 1.0 # kg
      pendulum_stick: 0.0001 # kg
      pendulum: 0.1 # kg
    inertia:
      cart: [0.00001, 0.00001, 0.00001] # kg*m^2
      pendulum_stick: [0.00001, 0.00001, 0.00001] # kg*m^2
      pendulum: [0.00001, 0.00001, 0.00001] # kg*m^2

  pin:
    nu: 1 # Number of control inputs
    actuated_joints: [0] # First joint

  mpc:
    Fmax: [80] # Maximum force
    N_horizon: 300 # Prediction horizon
    use_RTI: true # Use Real-Time Iteration
    mpc_timestep: 0.01 # seconds
    x0: [0.0, 3.14159265, 0.0, 0.0]
    x0_random: true # If true, x0 above will not be used
    x0_range: [[-1.0, 1.0], [-3.142, 3.142], [-0.5, 0.5], [-0.5, 0.5]] # Range for random x0
    x0_sampling: "uniform" # Only uniform for now
    Q_mat: [2000, 10000, 0.02, 0.02] # State cost weights
    R_mat: [0.02] # Input cost weights
    termination_cost: 0.1 # Tolerance for early termination cost
    solve_ocp: true # Enable if only a single step is required
    full_traj: true # If above is true, then this needs to be true as well
    
  plots:
    Cart Position: ["qpos", 0, "m"]
    Pendulum Angle: ["qpos", 1, "rad"]
    Cart Velocity: ["qvel", 0, "m/s"]
    Pendulum Angular Velocity: ["qvel", 1, "rad/s"]
    MPC Cost: ["cost", 0, "Cost"]
    Control Input: ["ctrl", 0, "N"]

# ----------------------------------------------------------------------------------------
# PENDULUM MODEL CONFIGURATION
# ----------------------------------------------------------------------------------------
pendulum:
  mujoco:
    urdf_available: false
    model_path: "models_xml/pendulum.xml"
    sim_timestep: 0.001 # seconds
    sim_duration: 5.0 # seconds
    sim_framerate: 30  # Hz
    render: true # Render simulation
    verbose: false # Print debug information
    resolution: [480, 640]

  model:
    name: "pendulum"
    mass:
      pendulum: 1 # kg
    inertia:
      pendulum: [0.00001, 0.00001, 0.00001] # kg*m^2

  pin:
    nu: 1 # Number of control inputs
    actuated_joints: [0] # First and only joint

  mpc:
    Fmax: [80] # Maximum force
    N_horizon: 600 # Prediction horizon
    use_RTI: true # Use Real-Time Iteration
    mpc_timestep: 0.002 # seconds
    x0: [0.0, 0.0]
    Q_mat: [2000, 0.02] # State cost weights
    R_mat: [0.02] # Input cost weights

  plots:
    Pendulum Angle: ["qpos", 0, "rad"]
    Pendulum Angular Velocity: ["qvel", 0, "rad/s"]
    MPC Cost: ["cost", 0, "Cost"]
    Control Input: ["ctrl", 0, "N"]

# ----------------------------------------------------------------------------------------
# DOUBLE PENDULUM MODEL CONFIGURATION
# ----------------------------------------------------------------------------------------
double_pendulum:
  mujoco:
    urdf_available: false
    model_path: "models_xml/double_pendulum.xml"
    sim_timestep: 0.001 # seconds
    sim_duration: 5.0 # seconds
    sim_framerate: 30  # Hz
    render: true # Render simulation
    verbose: false # Print debug information
    resolution: [480, 640]

  model:
    name: "double_pendulum"
    mass:
      pendulum_stick1: 0.0001 # kg
      pendulum1: 0.5 # kg
      pendulum_stick2: 0.0001 # kg
      pendulum2: 0.5 # kg
    inertia:
      pendulum_stick1: [0.00001, 0.00001, 0.00001] # kg*m^2
      pendulum1: [0.002, 0.002, 0.002] # kg*m^2
      pendulum_stick2: [0.00001, 0.00001, 0.00001] # kg*m^2
      pendulum2: [0.002, 0.002, 0.002] # kg*m^2

  pin:
    nu: 1 # Number of control inputs
    actuated_joints: [0] # First and only joint

  mpc:
    Fmax: [2000] # Maximum force
    N_horizon: 1000 # Prediction horizon
    use_RTI: true # Use Real-Time Iteration
    mpc_timestep: 0.001 # seconds
    x0: [0.0, 0.0, 0.0, 0.0]
    Q_mat: [2000, 3000, 0.02, 0.02] # State cost weights
    R_mat: [0.02] # Input cost weights

  plots:
    Pendulum 1 Angle: ["qpos", 0, "rad"]
    Pendulum 2 Angle: ["qpos", 1, "rad"]
    Pendulum 1 Angular Velocity: ["qvel", 0, "rad/s"]
    Pendulum 2 Angular Velocity: ["qvel", 1, "rad/s"]
    MPC Cost: ["cost", 0, "Cost"]
    Control Input: ["ctrl", 0, "N"]

# ----------------------------------------------------------------------------------------
# CARTPOLE DOUBLE PENDULUM MODEL CONFIGURATION
# ----------------------------------------------------------------------------------------
cartpole_double_pendulum:
  mujoco:
    urdf_available: false
    model_path: "models_xml/cartpole_double_pendulum.xml"
    sim_timestep: 0.001 # seconds
    sim_duration: 3.0 # seconds
    sim_framerate: 30  # Hz
    render: true # Render simulation
    verbose: false # Print debug information
    resolution: [480, 640]

  model:
    name: "cartpole_double_pendulum"
    mass:
      cart: 1.0 # kg
      pendulum_stick1: 0.0001 # kg
      pendulum1: 0.5 # kg
      pendulum_stick2: 0.0001 # kg
      pendulum2: 0.5 # kg
    inertia:
      cart: [0.00001, 0.00001, 0.00001] # kg*m^2
      pendulum_stick1: [0.00001, 0.00001, 0.00001] # kg*m^2
      pendulum1: [0.002, 0.002, 0.002] # kg*m^2
      pendulum_stick2: [0.00001, 0.00001, 0.00001] # kg*m^2
      pendulum2: [0.002, 0.002, 0.002] # kg*m^2

  pin:
    nu: 1 # Number of control inputs
    actuated_joints: [0] # First and only joint

  mpc:
    Fmax: [200] # Maximum force
    N_horizon: 3000 # Prediction horizon
    use_RTI: true # Use Real-Time Iteration
    mpc_timestep: 0.001 # seconds
    x0: [0.0, 3.14159265, 0.0, 0.0, 0.0, 0.0]
    Q_mat: [100, 300, 300, 0.02, 0.02, 0.02] # State cost weights
    R_mat: [0.02] # Input cost weights

  plots:
    Cart Position: ["qpos", 0, "m"]
    Pendulum 1 Angle: ["qpos", 1, "rad"]
    Pendulum 2 Angle: ["qpos", 2, "rad"]
    Cart Velocity: ["qvel", 0, "m/s"]
    Pendulum 1 Angular Velocity: ["qvel", 1, "rad/s"]
    Pendulum 2 Angular Velocity: ["qvel", 2, "rad/s"]
    MPC Cost: ["cost", 0, "Cost"]
    Control Input: ["ctrl", 0, "N"]

# ----------------------------------------------------------------------------------------
# Iiwa14 MODEL CONFIGURATION
# ----------------------------------------------------------------------------------------
iiwa14:
  mujoco:
    urdf_available: true
    menagerie_name: iiwa14_mj_description
    sim_timestep: 0.001 # seconds
    sim_duration: 1 # seconds
    sim_framerate: 30  # Hz
    render: true # Render simulation
    verbose: true # Print debug information
    resolution: [480, 640]

  model:
    name: "iiwa14"

  pin:
    nu: 7 # Number of control inputs
    actuated_joints: [0, 1, 2, 3, 4, 5, 6] # all 7 joints

  # mpc:
  #   Fmax: [320, 320, 176, 176, 110, 40, 40] # Maximum torque
  #   N_horizon: 800 # Prediction horizon
  #   use_RTI: true # Use Real-Time Iteration
  #   mpc_timestep: 0.001 # seconds
  #   x0: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  #   x0_random: false # If true, x0 above will not be used
  #   x0_range: [[-1.0, 1.0], [-3.142, 3.142], [-0.5, 0.5], [-0.5, 0.5]] # Range for random x0
  #   x0_sampling: "uniform" # Only uniform for now
  #   Q_mat: [2000, 5000, 2000, 5000, 2000, 3000, 100, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01] # State cost weights
  #   R_mat: [0.01, 0.01, 0.01, 0.01, 0.1, 0.01, 0.01] # Input cost weights
  
  mpc:
    Fmax: [320, 320, 176, 176, 110, 40, 40]
    N_horizon: 1000
    use_RTI: true
    mpc_timestep: 0.001
    x0: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    x0_random: false # If true, x0 above will not be used
    x0_range: [[-1.0, 1.0], [-3.142, 3.142], [-0.5, 0.5], [-0.5, 0.5]] # Range for random x0
    x0_sampling: "uniform" # Only uniform for now
    Q_mat: [2000.0, 4000.0, 1600.0, 4000.0, 1200.0, 4000.0, 800.0, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
    R_mat: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01]

  plots:
    Joint 1 Angle: ["qpos", 0, "rad"]
    Joint 2 Angle: ["qpos", 1, "rad"]
    Joint 3 Angle: ["qpos", 2, "rad"]
    Joint 4 Angle: ["qpos", 3, "rad"]
    Joint 5 Angle: ["qpos", 4, "rad"]
    Joint 6 Angle: ["qpos", 5, "rad"]
    Joint 7 Angle: ["qpos", 6, "rad"]
    Joint 1 Angular Velocity: ["qvel", 0, "rad/s"]
    Joint 2 Angular Velocity: ["qvel", 1, "rad/s"]
    Joint 3 Angular Velocity: ["qvel", 2, "rad/s"]
    Joint 4 Angular Velocity: ["qvel", 3, "rad/s"]
    Joint 5 Angular Velocity: ["qvel", 4, "rad/s"]
    Joint 6 Angular Velocity: ["qvel", 5, "rad/s"]
    Joint 7 Angular Velocity: ["qvel", 6, "rad/s"]
    MPC Cost: ["cost", 0, "Cost"]
    Control Input 1: ["ctrl", 0, "N"]
    Control Input 2: ["ctrl", 1, "N"]
    Control Input 3: ["ctrl", 2, "N"]
    Control Input 4: ["ctrl", 3, "N"]
    Control Input 5: ["ctrl", 4, "N"]
    Control Input 6: ["ctrl", 5, "N"]
    Control Input 7: ["ctrl", 6, "N"]