name: default
channels:
- conda-forge
- nodefaults
dependencies:
- python 3.11.*
- cmake >=3.27
- ninja >=1.11
- pkg-config *
- git *
- c-compiler *
- cxx-compiler *
- pip *
- setuptools *
- wheel *
- casadi *
- numpy <2
- scipy *
- matplotlib *
- pinocchio >=3.7.0,<4
- meshcat-python >=0.3.2,<0.4
- mujoco >=3.3.2,<4
- mediapy >=1.2.4,<2
- example-robot-data >=4.3.0,<5
- robot_descriptions >=1.21.0,<2
- pink >=3.4.0,<4
- plotly >=6.4.0,<7
- mplcursors >=0.7,<0.8
- meshcat-shapes >=1.0.0,<2
- loop-rate-limiters >=1.2.0,<2
- scikit-build >=0.17
- pip
- pip:
  - tqdm
  - torch>=2.2.2, <3
  - torchinfo>=1.8.0, <2

