[workspace]
name = "acados-pixi"
channels = ["conda-forge"]
platforms = ["osx-64", "linux-64"]
# platforms = ["linux-64"]

[dependencies]
# Core build tools
python = "3.11.*"
cmake = ">=3.27"
ninja = ">=1.11"
pkg-config = "*"
git = "*"
c-compiler = "*"
cxx-compiler = "*"

# Python deps for acados_template + examples
pip = "*"
setuptools = "*"
wheel = "*"
casadi = "*"
numpy = "<2"
scipy = "*"
matplotlib = "*"
pinocchio = ">=3.7.0,<4"
meshcat-python = ">=0.3.2,<0.4"
mujoco = ">=3.3.2,<4"
mediapy = ">=1.2.4,<2"
example-robot-data = ">=4.3.0,<5"
robot_descriptions = ">=1.21.0,<2"
pink = ">=3.4.0,<4"
plotly = ">=6.4.0,<7"
mplcursors = ">=0.7,<0.8"
meshcat-shapes = ">=1.0.0,<2"
loop-rate-limiters = ">=1.2.0,<2"
scikit-build = ">=0.17"
ipython = ">=9.10.0,<10"
tqdm = ">=4.67.3,<5"
pytorch = "2.9.1.*"
torchinfo = ">=1.8.0,<2"

[activation.env]
# Path to acados source (needed by acados_template)
ACADOS_SOURCE_DIR = "$PWD/external/acados"

# Shared libraries (Linux uses LD_LIBRARY_PATH, macOS uses DYLD_LIBRARY_PATH)
LD_LIBRARY_PATH   = "${PWD}/external/acados/lib:${LD_LIBRARY_PATH:-}"
# LD_LIBRARY_PATH   = "${PWD}/.pixi/envs/default/lib:${PWD}/external/acados/lib:${LD_LIBRARY_PATH:-}"
DYLD_LIBRARY_PATH = "${PWD}/external/acados/lib:${DYLD_LIBRARY_PATH:-}"

# Makes CMake-based downstream projects find acados automatically
CMAKE_PREFIX_PATH = "$PWD/external/acados:$CMAKE_PREFIX_PATH"

# (Optional) useful for pkg-config consumers
PKG_CONFIG_PATH = "$PWD/external/acados/lib/pkgconfig:$PKG_CONFIG_PATH"

# PATH = "$PWD/external/acados/bin:$PATH"
# =============================
# Force Pixi to use system GCC
# =============================(Need these for l4casadi install)
CC  = "/apps/generic/compiler/2025/software/linux-rhel8-x86_64_v3/gcc-8.5.0/gcc-12.4.0-ozeu7oz3fbajoamcr7yiorwpuhasqz5q/bin/gcc"
CXX = "/apps/generic/compiler/2025/software/linux-rhel8-x86_64_v3/gcc-8.5.0/gcc-12.4.0-ozeu7oz3fbajoamcr7yiorwpuhasqz5q/bin/g++"
PATH = "/apps/generic/compiler/2025/software/linux-rhel8-x86_64_v3/gcc-8.5.0/gcc-12.4.0-ozeu7oz3fbajoamcr7yiorwpuhasqz5q/bin:$PATH"

[tasks]
# Clone, build, install acados
acados_clone = "git clone --recursive https://github.com/acados/acados.git external/acados"
acados_checkout = "cd external/acados && git checkout dc5ca937b88ebfb8784aae5822c8918424f8f27f"
acados_build   = "cmake -S external/acados -B build/acados -DCMAKE_INSTALL_PREFIX=$PWD/external/acados -DCMAKE_BUILD_TYPE=Release -DBLASFEO_TARGET=X64_AUTOMATIC -DHPIPM_TARGET=GENERIC -DACADOS_EXAMPLES=OFF -DACADOS_UNIT_TESTS=OFF -DACADOS_NUM_THREADS=1 -DACADOS_WITH_OPENMP=ON"
acados_install = "make -C build/acados -j4 install"
acados_python = "pixi add --pypi \"acados_template @ file:///$PWD/external/acados/interfaces/acados_template\" --editable"

acados_full = "pixi run acados_clone && pixi run acados_checkout && pixi run acados_build && pixi run acados_install && pixi run acados_python"

# Clone, install l4casadi from source
l4casadi_clone = "git clone https://github.com/Nicosoh/l4casadi.git external/l4casadi"
l4casadi_python = "pip install external/l4casadi --no-build-isolation"

l4casadi_full = "pixi run l4casadi_clone && pixi run l4casadi_python"

# Full packages install
setup_full = "pixi run l4casadi_full && pixi run acados_full"

# Run the minimal Python example
minimal_example = "export DYLD_LIBRARY_PATH=\"$PWD/external/acados/lib:$DYLD_LIBRARY_PATH\" && python external/acados/examples/acados_python/getting_started/minimal_example_ocp.py"

# For cartpole
main_cartpole = "export DYLD_LIBRARY_PATH=\"$PWD/external/acados/lib:$DYLD_LIBRARY_PATH\" && python main.py cartpole"
viz_cartpole = "python pin_visualizer.py cartpole"

# For pendulum
main_pendulum = "export DYLD_LIBRARY_PATH=\"$PWD/external/acados/lib:$DYLD_LIBRARY_PATH\" && python main.py Pendulum"
viz_pendulum = "python pin_visualizer.py pendulum"

# For double_pendulum
main_double_pendulum = "export DYLD_LIBRARY_PATH=\"$PWD/external/acados/lib:$DYLD_LIBRARY_PATH\" && python main.py double_pendulum"
viz_double_pendulum = "python pin_visualizer.py double_pendulum"

# For cartpole_double_pendulum
main_cartpole_double_pendulum = "export DYLD_LIBRARY_PATH=\"$PWD/external/acados/lib:$DYLD_LIBRARY_PATH\" && python main.py cartpole_double_pendulum"
viz_cartpole_double_pendulum = "python pin_visualizer.py cartpole_double_pendulum"

# For iiwa14
main_iiwa14 = "export DYLD_LIBRARY_PATH=\"$PWD/external/acados/lib:$DYLD_LIBRARY_PATH\" && python main.py iiwa14"
viz_iiwa14 = "python pin_visualizer.py iiwa14"

# For two_dof_arm
main_twodofarm = "export DYLD_LIBRARY_PATH=\"$PWD/external/acados/lib:$DYLD_LIBRARY_PATH\" && python main.py TwoDofArm"
# main_twodofarm = "export DYLD_LIBRARY_PATH=\"$PWD/external/acados/lib:$DYLD_LIBRARY_PATH\" && python -m cProfile main.py TwoDofArm > output.txt"
viz_twodofarm = "python pin_visualizer.py twodofarm"

# For all models
data_collector = "export DYLD_LIBRARY_PATH=\"$PWD/external/acados/lib:$DYLD_LIBRARY_PATH\" && python -m data_collection.data_collector"
data_viz = "python -m data_collection.data_viz"

# Training model
train_model = "python -m neural_network.main train_model"

# Testing model
evaluate_model = "python -m neural_network.main evaluate_model"

# Replay from saved data
replay = "python replay.py"

# Run value iteration
VI = "export DYLD_LIBRARY_PATH=\"$PWD/external/acados/lib:$DYLD_LIBRARY_PATH\" && python -m value_iteration.value_iteration"
