[DATA]
dataset_class = iiwa14_eeTracker
data_path = 

[MODEL]
model_name = iiwa14Model
load_checkpoint = false
checkpoint_path = 

[TRAINING]
learning_rate = 0.0000005
batch_size = 256
num_epochs = 16
patience = 10
min_lr = 0.00000001

[LOSS]
; weight for stationary-point penalty
alpha = 0.01

[VAL]
val_interval = 1