[DATA]
dataset_class = PendulumDataset
data_path = data/2025-12-02_17-59-35_pendulum_data_collection/2025-12-02_17-59-35_pendulum_logs.npz
apply_scaling = False
scaling_type = normalize
scaling_range_X = [[-1, 1], [-1, 1]]
scaling_range_y = [0, 32]
X_min = [-3.2, -20.0]
X_max = [3.2, 20.0]
y_min = [0.0]
y_max = [1200.0]

[MODEL]
model_name = PendulumModel
load_checkpoint = True
checkpoint_path = /Users/nicodemussoh/Documents/mpc_MuJoCo/neural_network/output/2025-12-10_17-51-15_train_model/model_epoch_978.pt

[TRAINING]
learning_rate = 0.01
batch_size = 256
num_epochs = 1000
patience = 20

[LOSS]
; weight for stationary-point penalty
alpha = 1.0
; stationary point for pendulum (angle=0, angular_velocity=0)
x_s = [0.0, 0.0]
y_s = [0.0]

[VAL]
val_interval = 1