[DATA]
dataset_class = PendulumDataset
data_path = 

[MODEL]
model_name = PendulumModel
load_checkpoint = False
checkpoint_path = 

[TRAINING]
learning_rate = 0.00003
batch_size = 256
num_epochs = 16
patience = 10
min_lr = 0.0000001

[LOSS]
; weight for stationary-point penalty
alpha = 1.0
; stationary point for pendulum (angle=0, angular_velocity=0)
x_s = [0.0, 0.0]
y_s = [0.0]

[VAL]
val_interval = 1