[DATA]
dataset_class = PendulumDataset
data_path = data/2025-12-02_17-59-35_pendulum_data_collection/2025-12-02_17-59-35_pendulum_logs.npz
; apply_scaling_X = False
; apply_scaling_y = False
; scaling_type = normalize
; scaling_range_from_X = [[-3.2, -20.0], [3.2, 20.0]]
; scaling_range_from_y = [0.0, 32]
; scaling_range_to_X = [[-1, -1], [1, 1]]
; scaling_range_to_y = [0.0, 1200.0]

[MODEL]
model_name = PendulumModel
; model_name = PendulumModel_with_scaling
load_checkpoint = False
checkpoint_path = 

[TRAINING]
learning_rate = 0.001
batch_size = 256
num_epochs = 1000
patience = 10

[LOSS]
; weight for stationary-point penalty
alpha = 1.0
; stationary point for pendulum (angle=0, angular_velocity=0)
x_s = [0.0, 0.0]
y_s = [0.0]

[VAL]
val_interval = 1