[DATA]
dataset_class = TwoDofArmDataset
data_path = data/2026-01-08_15-52-42_twodofarm_data_collection/2026-01-08_15-52-42_twodofarm_logs.npz

[MODEL]
model_name = TwoDofArmModel
load_checkpoint = False
checkpoint_path = 

[TRAINING]
learning_rate = 0.001
batch_size = 256
num_epochs = 1000
patience = 10

[LOSS]
; weight for stationary-point penalty
alpha = 1.0
; stationary point for twodofarm (angle=0, angular_velocity=0)
x_s = [0.0, 0.0, 0.0, 0.0]
y_s = [0.0]

[VAL]
val_interval = 1