[DATA]
dataset_class = TwoDofArmDataset
data_path = value_iteration/output/2026-01-13_11-29-30_twodofarm_VI/loop_1/data_collection/2026-01-13_11-29-30_twodofarm_logs.npz
[MODEL]
model_name = TwoDofArmModel
load_checkpoint = false
checkpoint_path = 
[TRAINING]
learning_rate = 0.001
batch_size = 256
num_epochs = 200
patience = 10
min_lr = 0.000001

[LOSS]
; weight for stationary-point penalty
alpha = 0.1
; stationary point for twodofarm (angle=0, angular_velocity=0)
; x_s = [0.0, 0.0, 0.0, 0.0]
; y_s = [0.0]

[VAL]
val_interval = 1