[DATA]
dataset_class = TwoDofArmDataset_eeTracker
data_path = 
[MODEL]
model_name = TwoDofArmModel
load_checkpoint = false
checkpoint_path = 
[TRAINING]
learning_rate = 0.000005
batch_size = 256
num_epochs = 16
patience = 10
min_lr = 0.0000001

[LOSS]
; weight for stationary-point penalty
alpha = 0.01
; stationary point for twodofarm (angle=0, angular_velocity=0)
; x_s = [0.0, 0.0, 0.0, 0.0]
; y_s = [0.0]

[VAL]
val_interval = 1