# ----------------------------------------------------------------------------------------
# Iiwa14 MODEL CONFIGURATION
# ----------------------------------------------------------------------------------------
mujoco:
  sim_timestep: 0.001 # seconds
  sim_duration: 3.0 # seconds
  sim_framerate: 30  # Hz
  render: true # Render simulation
  verbose: false # Print debug information
  resolution: [480, 640]

model:
  name: "iiwa14"
  scene_path: 'kuka_iiwa_14/scene.xml'
  model_path: 'kuka_iiwa_14/iiwa14.xml'

pin:
  nu: 7 # Number of control inputs
  actuated_joints: [0, 1, 2, 3, 4, 5, 6] # all 7 joints

mpc:
  json_name: "main_controller"
  controller_name: "ManipulatorMPCController_eeTracker_point"
  # Fmax: [320, 320, 176, 176, 110, 40, 40]
  Fmax: [320, 320, 176, 176, 110, 40, 0]
  # xmax: [2.96706, 2.0944, 2.96706, 2.0944, 2.96706, 2.0944, 3.05433, # 170, 120, 170, 120, 170, 120, 175 deg
  #         1.48353, 1.48353, 1.74533, 1.309, 2.26893, 2.35619, 2.35619] # 85, 85, 100, 75, 130, 135, 135 deg/s  
  # xmax: [2.96706, 2.0944, 2.96706, 2.0944, 2.96706, 2.0944, 3.05433, # 170, 120, 170, 120, 170, 120, 175 deg
  #         0.741765, 0.741765, 0.872665, 0.6545 , 1.134465, 1.178095, 1.178095] # 42.5, 42.5, 50, 37.5, 65, 67.5, 67.5 deg/s
  xmax: [2.96706, 2.0944, 2.96706, 2.0944, 2.96706, 2.0944, 3.05433, # 170, 120, 170, 120, 170, 120, 175 deg
          0.49451, 0.49451, 0.58177667, 0.43633333, 0.75631, 0.78539667, 0.78539667] # 85, 85, 100, 75, 130, 135, 135 deg/s  
  N_horizon: 10
  use_RTI: false
  mpc_timestep: 0.01
  x0_q:
  - 2.2336594867603754
  - -1.2398713585640926
  - -2.447901147648798
  - -1.4186096594367918
  - -2.4435936844294397
  - -0.1718573151692402
  - -2.630778054021795
  x0_v:
  - 0.23386238848315588
  - 0.7045076025415209
  - 0.8948015852460431
  - -0.9882637748940568
  - 0.7932991218309093
  - -0.6961567233723367
  - 0.6823318551860205      # Inital joint velocity if random not true
  x0_q_random: true # If true, x0 above will not be used
  x0_range: [[[0.5, 0.1, 0.05], [0.7, 0.3, 0.2]], # Zone 0
            [[0.5, -0.3, 0.05], [0.7, -0.1, 0.2]]] # Zone 1
  x0_q_sampling: uniform # Only uniform for now
  yref_q:
  - -1.85035635014263
  - -2.0268714592974257
  - -1.621914795706807
  - 1.7261549688872626
  - -0.39566560596073863
  - 1.0604356090425728
  - -2.3767592325473874
  yref_q_random: true
  yref_range: [[[0.3, -0.3, 0.05], [0.6, -0.1, 0.2]], # Zone 0
            [[0.5, 0.1, 0.05], [0.7, 0.3, 0.2]]] # Zone 1
  yref_q_sampling: uniform
  zone_probability: [0.5, 0.5]
  terminal_cost: true
  Q_mat: [5000, 5000, 5000] # State cost weights for ee tracking
  Q_dot_mat: [100, 100, 75, 75, 25, 25, 25] # Velocity state cost weights for joints
  # Q_dot_mat: [500, 500, 375, 375, 125, 125, 125]
  R_mat: [0.0001, 0.0001, 0.0001, 0.0001, 0.001, 0.0001, 0.0001]
  early_termination_cost: true # Enable early termination based on cost
  termination_cost: 0.05 # Tolerance for early termination cost
  early_termination_state: false # Enable early termination based on state
  termination_state: 0.01 # Tolerance for early termination state
  solve_ocp: false # Enable if only a single step is required
  full_traj: true # If above is true, then this needs to be true as well
  IK_required: true # Enable inverse kinematics in MPC setup (only for manipulators)
  levenberg_marquardt: 10.0
  regularize_method: 'NO_REGULARIZE'
  nlp_solver_warm_start_first_qp_from_nlp: true
  nlp_solver_warm_start_first_qp: true
  qp_solver_warm_start: 1

data:
  save_yaml: false # only work in data collection mode
  save_data: true

IK:
  IK_required: true # Enable inverse kinematics in MPC setup (only for manipulators)
  output_xyz: true 
  point_reference: true
  stop_threshold: 0.001
  visualize_IK: false
  max_iterations: 100000          # max iters before considering goal not reachable
  velocity_threshold: 0.001    # min velocity from solve_ik before considering goal not reachable
  velocitylimit: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0] # rad/s
  limit_acceleration: false
  accelerationlimit: [50.0, 50.0, 50.0, 50.0, 50.0, 50.0, 50.0] # rad/s^2\
  safety_distance: 0.05 # minimum distance to maintain from obstacles

collision:
  collision_avoidance_obstacle: true
  collision_avoidance_ground: true

  srdf_path: "models_xml/kuka_iiwa_14/iiwa14.srdf"
  links:  # Frames from pinocchio model
    cap3:
      from: c11
      to: c12
      radius: 0.12

    cap5:
      from: c21
      to: c22
      radius: 0.10
    
    cap7:
      from: c31
      to: c32
      radius: 0.06

  obstacles_random: false
  obstacles_num: 1
  obstacles_range: [[0.3, 0.0, 0.0], [0.8, 0.0, 0.60],       # [[from_min_x,y,z, from_max_x,y,z], 
                    [0.3, 0.0, 0.0], [0.8, 0.0, 0.60],       # [to_min_x,y,z, to_max_x,y,z], 
                    [0.05, 0.05]]                             # [radius_min, radius_max]]
  obstacles_sampling: uniform

  obstacles: # Only if obstacles_random: true and will be replaced
    obs1:
      from: [0.2, 0.0, 0.2]
      to:   [1.0, 0.0, 0.2]
      radius: 0.05

  ground_plane: [0, 0, 1, 0]

  collision_pairs: 
    obstacle: [[cap3, obs1],
              [cap5, obs1],
              [cap7, obs1]]
    ground: [[cap5, ground],
             [cap7, ground]]

VI:
  ground_truth_controller: true

  changes:
    mpc:
      controller_name: "ManipulatorMPCController_eeTracker_point"
      N_horizon: 25
      mpc_timestep: 0.1 # seconds
      terminal_cost: true
      json_name: "GT_controller"

NN:
  model_name: "iiwa14ModelAcados"
  checkpoint_path: ""

plots:
  EndEffector X Position: ["xyzpos", 0, "m"]
  EndEffector Y Position: ["xyzpos", 1, "m"]
  EndEffector Z Position: ["xyzpos", 2, "m"]
  Joint 1 Angle: ["qpos", 0, "rad"]
  Joint 2 Angle: ["qpos", 1, "rad"]
  Joint 3 Angle: ["qpos", 2, "rad"]
  Joint 4 Angle: ["qpos", 3, "rad"]
  Joint 5 Angle: ["qpos", 4, "rad"]
  Joint 6 Angle: ["qpos", 5, "rad"]
  Joint 7 Angle: ["qpos", 6, "rad"]
  Joint 1 Angular Velocity: ["qvel", 0, "rad/s"]
  Joint 2 Angular Velocity: ["qvel", 1, "rad/s"]
  Joint 3 Angular Velocity: ["qvel", 2, "rad/s"]
  Joint 4 Angular Velocity: ["qvel", 3, "rad/s"]
  Joint 5 Angular Velocity: ["qvel", 4, "rad/s"]
  Joint 6 Angular Velocity: ["qvel", 5, "rad/s"]
  Joint 7 Angular Velocity: ["qvel", 6, "rad/s"]
  Control Input 1: ["ctrl", 0, "N"]
  Control Input 2: ["ctrl", 1, "N"]
  Control Input 3: ["ctrl", 2, "N"]
  Control Input 4: ["ctrl", 3, "N"]
  Control Input 5: ["ctrl", 4, "N"]
  Control Input 6: ["ctrl", 5, "N"]
  Control Input 7: ["ctrl", 6, "N"]
  Squared Distance 1: ["sq_dist", 0, "m^2"]
  Squared Distance 2: ["sq_dist", 1, "m^2"]
  Squared Distance 3: ["sq_dist", 2, "m^2"]
  Distance 1: ["sq_dist", 3, "m"]
  Distance 2: ["sq_dist", 4, "m"]