# ----------------------------------------------------------------------------------------
# PENDULUM MODEL CONFIGURATION
# ----------------------------------------------------------------------------------------
mujoco:
  urdf_available: false
  model_path: "models_xml/pendulum.xml"
  sim_timestep: 0.001 # seconds
  sim_duration: 5.0 # seconds
  sim_framerate: 30  # Hz
  render: true # Render simulation
  verbose: false # Print debug information
  resolution: [480, 640]

model:
  name: "Pendulum"
  model_path: "pendulum.xml"
  scene_path: "pendulum.xml"
  mass:
    pendulum: 0.1 # kg
  inertia:
    pendulum: [0.00001, 0.00001, 0.00001] # kg*m^2

pin:
  nu: 1 # Number of control inputs
  actuated_joints: [0] # First and only joint

mpc:
  json_name: "main"
  controller_name: "BaseMPCController"
  # controller_name: "NNMPCController"
  Fmax: [1] # Maximum force
  xmax: [6.0, 5.0]
  N_horizon: 5 # Prediction horizon
  use_RTI: False # Use Real-Time Iteration
  mpc_timestep: 0.01 # seconds
  x0: [3.142, 0.0]
  # x0: [-1.702437617635593, 0.15633105949216464]
  x0_random: false # If true, x0 above will not be used
  x0_range: [[-3.142, 3.142], [-5.0, 5.0]] # Range for random x0
  x0_sampling: "uniform" # Only uniform for now
  yref_random: false
  yref: [0.0, 0.0, 0.0] # [angle, angular_velocity, input]
  Q_mat: [2000, 0.02] # State cost weights
  R_mat: [20] # Input cost weights
  terminal_cost: false
  early_termination_cost: false # Enable early termination based on cost
  termination_cost: 0.1 # Tolerance for early termination cost
  early_termination_state: false
  termination_state: 0.01
  solve_ocp: false # Enable if only a single step is required
  full_traj: true # If above is true, then this needs to be true as well
  IK_required: false # Enable inverse kinematics in MPC setup (only for manipulators)
  levenberg_marquardt: 0.0
  regularize_method: 'NO_REGULARIZE'
  nlp_solver_warm_start_first_qp_from_nlp: false
  nlp_solver_warm_start_first_qp: false
  qp_solver_warm_start: 0

IK:
  IK_required: false
  point_reference: false
  output_xyz: false

data:
  save_data: true

collision:
  collision_avoidance: false

# Ground truth controller
VI:
  ground_truth_controller: true

  changes:
    mpc:
      controller_name: "BaseMPCController"
      N_horizon: 25
      mpc_timestep: 0.1 # seconds
      terminal_cost: true
      json_name: "GT_controller"

NN:
  model_name: "PendulumModelAcados"
  checkpoint_path: ""

plots:
  Pendulum Angle: ["qpos", 0, "rad"]
  Pendulum Angular Velocity: ["qvel", 0, "rad/s"]
  Control Input: ["ctrl", 0, "Nm"]