# ----------------------------------------------------------------------------------------
# 2 DOF ARM CONFIGURATION
# ----------------------------------------------------------------------------------------
mujoco:
  urdf_available: false
  model_path: "models_xml/2dof_arm.xml"
  sim_timestep: 0.001 # seconds
  sim_duration: 5.0 # seconds
  sim_framerate: 30  # Hz
  render: true # Render simulation
  verbose: false # Print debug information
  resolution: [480, 640]

model:
  name: "two_dof_arm"
  mass:
    pendulum_stick1: 0.1 # kg
    pendulum_stick2: 0.1 # kg
  inertia:
    pendulum_stick1: [0.002, 0.002, 0.002] # kg*m^2
    pendulum_stick2: [0.002, 0.002, 0.002] # kg*m^2

pin:
  nu: 2 # Number of control inputs
  actuated_joints: [0, 1] # First and second joints

mpc:
  json_name: "main_controller"
  controller_name: "ManipulatorMPCController_eeTracker_point"
  # controller_name: "NNManipulatorMPCController_eeTracker_point"
  Fmax: [5, 5] # Maximum force
  xmax: [3.142, 3.142, 1.0, 1.0]
  N_horizon: 20 # Prediction horizon
  use_RTI: false # Use Real-Time Iteration
  mpc_timestep: 0.01 # seconds  
  x0_q: [0.7, -1.0]
  x0_v: [0, 0]      # Inital joint velocity if random not true
  x0_q_random: true # If true, x0 above will not be used
  x0_range: [[[0.0, 0.0, 1.3], [0.8, 0.0, 1.7]], # Zone 1 # Range for random x0 [[min_xyz], [max_xyz]]
              [[0.0, 0.0, 1.3], [0.8, 0.0, 1.7]], # Zone 2 [[min_xyz], [max_xyz]]
              [[-0.8, 0.0, 1.3], [0.0, 0.0, 1.7]],
              [[-0.8, 0.0, 1.3], [0.0, 0.0, 1.7]],
              [[-0.8, 0.0, 1.25], [-0.45, 0.0, 1.7]]] 
  # x0_range: [[-0.8, 0.0, 0.8], [0.8, 0.0, 1.8]]
  x0_q_sampling: uniform # Only uniform for now
  yref_q: [-0.7, 1.0]
  yref_q_random: true
  yref_range: [[[-0.8, 0.0, 0.8], [0.0, 0.0, 1.3]],
                [[-0.8, 0.0, 1.3], [0.0, 0.0, 1.7]], # Zone 1,2 [[min_xyz], [max_xyz]]
                [[0.0, 0.0, 1.3], [0.8, 0.0, 1.7]],
                [[0.0, 0.0, 0.8], [0.8, 0.0, 1.3]],
                [[-0.4, 0.0, 1.25], [0.0, 0.0, 1.55]]]
  # yref_range: [[-0.8, 0.0, 0.8], [0.8, 0.0, 1.8]]
  yref_q_sampling: uniform
  zone_probability: [0.1, 0.25, 0.25, 0.1, 0.3]
  Q_mat: [50, 50, 50] # State cost weights for ee tracking
  Q_dot_mat: [0.002, 0.002] # Velocity state cost weights for joints
  R_mat: [0.001, 0.001] # Input cost weights
  terminal_cost: false
  early_termination_cost: true # Enable early termination based on cost
  termination_cost: 0.005 # Tolerance for early termination cost
  early_termination_state: false # Enable early termination based on state
  termination_state: 0.01 # Tolerance for early termination state
  solve_ocp: false # Enable if only a single step is required
  full_traj: true # If above is true, then this needs to be true as well
  levenberg_marquardt: 10.0
  regularize_method: 'NO_REGULARIZE'
  nlp_solver_warm_start_first_qp_from_nlp: true
  nlp_solver_warm_start_first_qp: true
  qp_solver_warm_start: 1

data:
  save_data: true

IK:
  IK_required: true # Enable inverse kinematics in MPC setup (only for manipulators)
  output_xyz: true 
  point_reference: true
  stop_threshold: 0.001
  visualize_IK: false
  max_iterations: 100000          # max iters before considering goal not reachable
  velocity_threshold: 0.001    # min velocity from solve_ik before considering goal not reachable
  velocitylimit: [1.0, 1.0] # rad/s
  limit_acceleration: false
  accelerationlimit: [50.0, 50.0] # rad/s^2\
  safety_distance: 0.05 # minimum distance to maintain from obstacles

collision:
  collision_avoidance: true
  links:  # Frames from pinocchio model
    link1:
      from: universe
      to: j_1
      radius: 0.1

    link2:
      from: j_1
      to: j_2
      radius: 0.1

  obstacles_random: false
  obstacles_num: 1
  obstacles_range: [[0.3, 0.0, 0.0], [0.8, 0.0, 0.60],       # [[from_min_x,y,z, from_max_x,y,z], 
                    [0.3, 0.0, 0.0], [0.8, 0.0, 0.60],       # [to_min_x,y,z, to_max_x,y,z], 
                    [0.05, 0.05]]                             # [radius_min, radius_max]]
  obstacles_sampling: uniform

  obstacles: # Only if obstacles_random: true and will be replaced
    obs1:
      from: [0.0, 0.0, 1.2]
      to:   [0.0, 0.0, 1.8]
      radius: 0.1

  collision_pairs: [[link2, obs1],
                  [link1, obs1]]

# Ground truth controller
VI:
  ground_truth_controller: true

  changes:
    mpc:
      controller_name: "ManipulatorMPCController_eeTracker_point"
      N_horizon: 25
      mpc_timestep: 0.08 # seconds
      terminal_cost: false
      json_name: "GT_controller"

NN:
  model_name: "TwoDofArmModelAcados"
  checkpoint_path: "value_iteration/output/2026-02-07_15-49-41_TwoDofArm_VI/loop_13/training/model_epoch_16.pt"

plots:
  EndEffector X Position: ["xyzpos", 0, "m"]
  EndEffector Y Position: ["xyzpos", 1, "m"]
  EndEffector Z Position: ["xyzpos", 2, "m"]
  Joint 1 Angle: ["qpos", 0, "rad"]
  Joint 2 Angle: ["qpos", 1, "rad"]
  Joint 1 Angular Velocity: ["qvel", 0, "rad/s"]
  Joint 2 Angular Velocity: ["qvel", 1, "rad/s"]
  # Stage MPC Cost: ["stage_cost", 0, "Stage Cost"]
  # Terminal MPC Cost: ["terminal_cost", 0, "Terminal Cost"]
  # Total MPC Cost: ["total_cost", 0, "Total Cost"]
  Control Input 1: ["ctrl", 0, "Nm"]
  Control Input 2: ["ctrl", 1, "Nm"]
  Squared Distance 1: ["sq_dist", 0, "m^2"]
  Squared Distance 2: ["sq_dist", 1, "m^2"]
